version: "3.8"
volumes:
  postgres_data:
    driver: local

services:

  postgres:
    container_name: Froom-Postgres
    image: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  category-module:
    build: ./CategoryClassification
    container_name: Froom-CategoryModule
    env_file:
      - .env
    ports:
      - "5000:5000"

  color-module:
    build: ./ColorClassification
    container_name: Froom-ColorModule
    env_file:
      - .env
    ports:
      - "5001:5000"